name: Build and Push Docker Image

# Run this workflow whenever you push code to the main branch
on:
  push:
    branches:
      - main  # Or replace 'main' with your default branch name

jobs:
  build:
    # Use a GitHub-hosted Ubuntu server to run the workflow
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the latest code in your repo
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub using the secrets you added
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t kasun594/Raspberry_pi_AI_Course:latest .

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push kasun594/Raspberry_pi_AI_Course:latest
